CREATE TABLE RUTINA(
ID_RUT SERIAL,
NOMBRE VARCHAR(255),
TIEMPO TIME NOT NULL,

PRIMARY KEY(ID_RUT)
);


CREATE TABLE PERSONA(
COD_PERS BIGINT UNIQUE,
CEDULA BIGINT NOT NULL,
NOMBRE VARCHAR(255) NOT NULL,
APELLIDO VARCHAR(255) NOT NULL,
EDAD INT NOT NULL,
DIRECCION VARCHAR(255),
TELEFONO BIGINT NOT NULL,
CORREO VARCHAR(255) NOT NULL,
USERNAME VARCHAR(255) UNIQUE,
PASSWORD VARCHAR(255) NOT NULL

);

CREATE TABLE INSTRUCTOR(
ID_INS SERIAL,

PRIMARY KEY(ID_INS),
FOREIGN KEY(ID_INS) REFERENCES PERSONA(COD_PERS)
);

CREATE TABLE USUARIO(
ID_USUA SERIAL,
DAT_MED TEXT,
ID_DESC INT,

PRIMARY KEY(ID_USUA),
FOREIGN KEY(ID_USUA) REFERENCES PERSONA(COD_PERS)
);


CREATE TABLE RUTXUSUA(
ID_RUT2 BIGINT NOT NULL,
ID_USUA2 BIGINT NOT NULL,

FOREIGN KEY(ID_RUT2) REFERENCES RUTINA(ID_RUT),
FOREIGN KEY(ID_USUA2) REFERENCES USUARIO(ID_USUA)
);

CREATE TABLE ASISTENCIA(
ID SERIAL,
ID_USUA3 BIGINT UNIQUE,
FECHA DATE NOT NULL,
HORA TIME NOT NULL,

PRIMARY KEY(ID),
FOREIGN KEY(ID_USUA3) REFERENCES USUARIO(ID_USUA)
);

CREATE TABLE ADMINISTRADOR(
ID_ADMIN SERIAL,

PRIMARY KEY(ID_ADMIN),
FOREIGN KEY(ID_ADMIN) REFERENCES PERSONA(COD_PERS)
);

CREATE TABLE COMENTARIOS(
ID_USUA INT UNIQUE NOT NULL,
ID_INS INT UNIQUE NOT NULL,
ESTRELLAS INT NOT NULL,

FOREIGN KEY(ID_USUA) REFERENCES USUARIO(ID_USUA),
FOREIGN KEY(ID_INS) REFERENCES INSTRUCTOR(ID_INS)
);

CREATE TABLE FACTURA(
ID_FAC SERIAL,
ID_USUA INT NOT NULL,
ID_DESCUENTO INT NULL,
ID_PREC INT NOT NULL,
MONTO BIGINT NOT NULL,
FECHA DATE NOT NULL,
ESTADO VARCHAR(1) DEFAULT 'P',
PRIMARY KEY(ID_FAC),
CHECK (ESTADO='P' OR ESTADO='A')
);


CREATE TABLE DESCUENTO(	
ID_DESC SERIAL,
NOMBRE VARCHAR(255),
MONTO BIGINT NOT NULL,
PRIMARY KEY(ID_DESC)
);

CREATE TABLE PRECIO(
ID_PRE SERIAL,
nombre VARCHAR(255),
DIAS INT NOT NULL,
PRECIO BIGINT NOT NULL,
PRIMARY KEY(ID_PRE)
);

ALTER TABLE FACTURA RENAME COLUMN FECHA TO FECHA_INICIAL;
ALTER TABLE FACTURA ADD COLUMN FECHA_FINAL DATE NOT NULL;
alter table USUARIO
  add constraint FOREGINDESC
  foreign key (ID_DESC)
  references DESCUENTO (ID_DESC);