CREATE TABLE RUTINA(
ID_RUT SERIAL,
NOMBRE VARCHAR(255),
TIEMPO TIME NOT NULL,

PRIMARY KEY(ID_RUT)
);


CREATE TABLE PERSONA(
COD_PERS BIGINT UNIQUE,
CEDULA BIGINT NOT NULL,
NOMBRE VARCHAR(255) NOT NULL,
APELLIDO VARCHAR(255) NOT NULL,
EDAD INT NOT NULL,
DIRECCION VARCHAR(255),
TELEFONO BIGINT NOT NULL,
CORREO VARCHAR(255) NOT NULL,
USERNAME VARCHAR(255) UNIQUE,
PASSWORD VARCHAR(255) NOT NULL

);


CREATE TABLE USUARIO(
ID_USUA SERIAL,
DAT_MED TEXT,

PRIMARY KEY(ID_USUA),
FOREIGN KEY(ID_USUA) REFERENCES PERSONA(COD_PERS)
);


CREATE TABLE RUTXUSUA(
ID_RUT2 BIGINT NOT NULL,
ID_USUA2 BIGINT NOT NULL,

FOREIGN KEY(ID_RUT2) REFERENCES RUTINA(ID_RUT),
FOREIGN KEY(ID_USUA2) REFERENCES USUARIO(ID_USUA)
);


CREATE TABLE ADMINISTRADOR(
ID_ADMIN SERIAL,

PRIMARY KEY(ID_ADMIN),
FOREIGN KEY(ID_ADMIN) REFERENCES PERSONA(COD_PERS)
);


CREATE TABLE FACTURA(
ID_FAC SERIAL,
ID_USUA INT NOT NULL UNIQUE,
ID_DESCUENTO INT NOT NULL UNIQUE,
MONTO BIGINT NOT NULL UNIQUE,
FECHA DATE NOT NULL,
ESTADO VARCHAR(1) DEFAULT 'P',

PRIMARY KEY(ID_FAC),
FOREIGN KEY(ID_USUA) REFERENCES USUARIO(ID_USUA),
CHECK (ESTADO='P' OR ESTADO='A')
);


CREATE TABLE DESCUENTO(	
ID_DESC SERIAL,
NOMBRE VARCHAR(255),
MONTO BIGINT NOT NULL,

PRIMARY KEY(ID_DESC),
FOREIGN KEY(ID_DESC) REFERENCES FACTURA(ID_DESCUENTO)
);


CREATE TABLE VENTA(
ID_VENTA SERIAL,
MONTO BIGINT NOT NULL,

PRIMARY KEY(ID_VENTA),
FOREIGN KEY(ID_VENTA) REFERENCES FACTURA(MONTO)
);

CREATE TABLE PRECIO(
ID_PRE SERIAL,
PRECIO BIGINT NOT NULL,

PRIMARY KEY(ID_PRE),
FOREIGN KEY(ID_PRE) REFERENCES FACTURA(ID_FAC)
);